---
baseurl: "http://www.example.com"

title: "Example"
metaDataFormat: "yaml"
DefaultContentLanguage: sv

Multilingual:
  sv:
    weight: 1
    languageCode: "sv-SE"

  en:
    weight: 2
    languageCode: "en-US"

